"""
Django settings for myrecipe project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from pathlib import Path
import os
import dj_database_url
from decouple import config,Csv
import cloudinary
import cloudinary.uploader
import cloudinary.api
import environ  # <-- Updated!
from django.core.management.utils import get_random_secret_key

# Initialize environment variables
env = environ.Env()
environ.Env.read_env()  # Reads the .env file

# Get the MODE setting (dev or prod)
MODE = env.str('MODE', default='dev')

# SECRET_KEY (keep this secret for production)
SECRET_KEY = env.str('SECRET_KEY', default=get_random_secret_key())

# DEBUG flag
DEBUG = env.bool('DEBUG', default=False)

# Set ALLOWED_HOSTS based on the environment
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'recipe-home.fly.dev']
CSRF_TRUSTED_ORIGINS = ['https://fly.io/apps/recipe-home']

# Database settings
if MODE == "dev":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env.str('DB_NAME', default='recipedata'),
            'USER': env.str('DB_USER', default='postgres'),
            'PASSWORD': env.str('DB_PASSWORD', default='password'),
            'HOST': env.str('DB_HOST', default='localhost'),
            'PORT': env.str('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=env.str('DATABASE_URL')
        )
    }